[buildPlans.IosevkaCustomFlat]
family = "Iosevka Custom Flat"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustomFlat.variants.design]
f = "flat-hook-serifless-crossbar-at-x-height"
g = "double-storey"
j = "flat-hook-serifed"
r = "hookless-serifless"
t = "flat-hook"
y = "straight-turn-serifless"
long-s = "flat-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-lambda = "straight-turn"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
three = "flat-top-serifless"
six = "closed-contour"
nine = "closed-contour"
guillemet = "straight"
percent = "rings-continuous-slash"

[buildPlans.IosevkaCustomFlat.variants.italic]
f = "tailed"
g = "single-storey-serifless"
j = "serifed"
r = "serifless"
t = "bent-hook"
y = "cursive-serifless"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
cyrl-u = "cursive-serifless"

[buildPlans.IosevkaCustomFlat.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustomFlat.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustomFlat.widths.normal]
shape = 548
menu = 5
css = "normal"

[buildPlans.IosevkaCustomFlat.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustomFlat.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
