filetype plugin indent on
syntax on
set number relativenumber
set splitbelow splitright
set cursorline
set nostartofline
set tabstop=4 expandtab
set incsearch
set hlsearch
set ignorecase
set smartcase
set fillchars+=vert:\│
set hidden
set showcmd

set title
set titlestring=VIM:\ %-25.55F\%a%r%m titlelen=70

set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath^=$XDG_DATA_HOME/vim
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

if empty(glob('~/.local/share/vim/autoload/plug.vim'))
    silent !curl -fLo ~/.local/share/vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

Plug 'vim-airline/vim-airline'
Plug 'arcticicestudio/nord-vim'
Plug 'tpope/vim-fugitive'
Plug 'ervandew/supertab'
" Refer to https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions for
" how to install COC plugins
Plug 'neoclide/coc.nvim', { 'branch' : 'release' }
Plug 'junegunn/fzf', { 'do' : { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()

colorscheme nord
let g:airline_powerline_fonts=1
let g:airline_theme='nord'
" let g:airline#extensions#tabline#enabled = 1

set encoding=utf-8

" Insert newline without entering insert mode
map <Enter> o<ESC>
map <S-Enter> O<ESC>

" Keybinds for window navigation
" use :redraw! to force redraw the screen instead
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Clear last search with Ctrl+/
noremap <silent> <C-_> :let @/ = ""<CR>

" Keybind to access buffer list and switch buffers
" nnoremap <leader>l :ls<CR>:b<space>

" fzf configuration
let $BAT_THEME = "Nord"
let $FZF_DEFAULT_COMMAND = "rg --files --hidden --no-ignore --glob '!.git/*'"
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
" Put {'options': ['--no-unicode']} in with_preview() to disable unicode
let g:fzf_layout = { 'down': '~30%' }
" fzf.vim keybinds
nnoremap <leader>l :Buffers<CR>
nnoremap <leader>p :Files<CR>
" tip: use :cd to change directory

nmap <F8> :set paste<CR>i
imap <F8> <ESC>:set paste<CR>i<Right>
au InsertLeave * set nopaste
