#!/bin/sh

# For use by neomutt
# Opens attachments in tmpdir (see neomuttrc) and prevents duplicates on subsequent runs
if [ -z "$1" ]
then
        echo "No arguments supplied"
else
        file="/home/nate/.cache/neomutt/zoho/temp/$(basename "$1")"
        rm -f "$file"
        cp "$1" "$file"
        xdg-open "$file" > /dev/null 2>&1 &
fi
