vim.o.number = true
vim.o.relativenumber = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.cursorline = true
vim.o.startofline = false
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.incsearch = true
vim.o.hlsearch = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.hidden = true
vim.o.showcmd = true
vim.o.encoding = "utf-8"
vim.o.guicursor = ""
vim.o.mouse = ""
vim.o.completeopt = "menuone,noselect"
vim.o.pumheight = 10
-- vim.o.pummaxwidth = 40 -- available in version 0.12

-- NERDTree-lookalike Netrw config
-- vim.g.netrw_banner = 0
-- vim.g.netrw_liststyle = 3
-- vim.g.netrw_browse_split = 4
-- vim.g.netrw_fastbrowse = 0
-- vim.g.netrw_altv = 1
-- vim.g.netrw_winsize = -25
