#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d $(seq 1 10)

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         36

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_monocle_padding  0
bspc config bottom_monocle_padding 0

bspc config normal_border_color   '#45403d'
bspc config active_border_color   '#1d2021'
bspc config focused_border_color  '#d8a657'

bspc config external_rules_command ~/.config/bspwm/external-rules
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# wmname LG3D

$HOME/.local/bin/polybar-launch
