[buildPlans.iosevka]
family = "Iosevka"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka.variants.design]
g = "double-storey"
eszet = "longs-s-lig-serifless"
zero = "tall-slashed"
two = "straight-neck"
three = "flat-top"
five = "upright-flat"
six = "closed-contour"
nine = "closed-contour"
percent = "rings-continuous-slash"

[buildPlans.iosevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka.widths.normal]
shape = 560
menu = 5
css = "normal"

[buildPlans.iosevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
